name: 'Build WP theme'
inputs:
  legacy-peer-deps:
    description: 'Install node dependencies with legacy peer dependencies'
    required: true
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install node dependencies (legacy)
      if: inputs.legacy-peer-deps == 'true'
      shell: bash
      run: |
        npm install --frozen-lockfile --legacy-peer-deps
        npm --prefix ./wordpress install --frozen-lockfile --legacy-peer-deps

    - name: Install node dependencies
      if: inputs.legacy-peer-deps != 'true'
      shell: bash
      run: |
        npm install --frozen-lockfile
        npm --prefix ./wordpress install --frozen-lockfile

    - name: Build assets
      shell: bash
      run: npm run build
      working-directory: ./wordpress

    - name: Save built artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wp-theme-assets
        path: |
          ./wordpress/theme/static
