name: 'Deploy Next.js'
description: 'Deploy Next.js on any Server'
inputs:
  NEXT_SSH_PRIVATE_KEY:
    description: 'Private key of the SSH user to deploy'
    required: true
  NEXT_SSH_USER:
    description: 'SSH user'
    required: true
  NEXT_SSH_HOST:
    description: 'SSH Host (IP adress)'
    required: true
  NEXT_SSH_PORT:
    description: 'SSH Port (default: 22)'
    required: false
    default: 22
  NEXT_SSH_PATH:
    description: 'Next absolute path on remote server'
    required: true
  NEXT_ENV:
    description: 'Next environment: local, development (default), staging or production'
    required: false
    default: 'development'
  NEXT_URL:
    description: 'Next URL'
    required: true
  WORDPRESS_URL:
    description: 'WordPress URL'
    required: true
  PM2_APP_NAME:
    description: 'PM2 app name'
    required: false
    default: ''
  legacy-peer-deps:
    description: 'Install node dependencies with legacy peer dependencies'
    required: true
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install node dependencies (legacy)
      if: inputs.legacy-peer-deps == 'true'
      shell: bash
      run: npm install --legacy-peer-deps

    - name: Install node dependencies
      if: inputs.legacy-peer-deps != 'true'
      shell: bash
      run: npm install

    - name: Copy environment file
      shell: bash
      run: cp .env.next.example .env

    - name: Build Next
      shell: bash
      run: WORDPRESS_URL=${{ inputs.WORDPRESS_URL }} NEXT_URL=${{ inputs.NEXT_URL }} NODE_ENV=production npm run build

    - name: Deploy Next environment file (if does not exist)
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ inputs.NEXT_SSH_PRIVATE_KEY }}
        REMOTE_USER: ${{ inputs.NEXT_SSH_USER }}
        REMOTE_HOST: ${{ inputs.NEXT_SSH_HOST }}
        REMOTE_PORT: ${{ inputs.NEXT_SSH_PORT }}
        ARGS: -aulrqtvz --ignore-existing
        SOURCE: .env
        TARGET: ${{ inputs.NEXT_SSH_PATH }}/.env

    - name: Deploy Next files
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ inputs.NEXT_SSH_PRIVATE_KEY }}
        REMOTE_USER: ${{ inputs.NEXT_SSH_USER }}
        REMOTE_HOST: ${{ inputs.NEXT_SSH_HOST }}
        REMOTE_PORT: ${{ inputs.NEXT_SSH_PORT }}
        ARGS: -aulrqtvz
        SOURCE: .
        TARGET: ${{ inputs.NEXT_SSH_PATH }}
        EXCLUDE: '.git*, .*ignore, .storybook, .vscode, docs, generators, wiki, .editorconfig, .env, .env.*.example, README.md, next-env.d.ts, vercel.json, wordpress'

    - name: Deploy WordPress files used by next
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ inputs.NEXT_SSH_PRIVATE_KEY }}
        REMOTE_USER: ${{ inputs.NEXT_SSH_USER }}
        REMOTE_HOST: ${{ inputs.NEXT_SSH_HOST }}
        REMOTE_PORT: ${{ inputs.NEXT_SSH_PORT }}
        ARGS: -aulrqtvz --mkpath
        SOURCE: './wordpress/theme/lib/editor/'
        TARGET: ${{ inputs.NEXT_SSH_PATH }}/wordpress/theme/lib/editor/
        EXCLUDE: '*.php'

    - name: Deploy WordPress files used by next
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ inputs.NEXT_SSH_PRIVATE_KEY }}
        REMOTE_USER: ${{ inputs.NEXT_SSH_USER }}
        REMOTE_HOST: ${{ inputs.NEXT_SSH_HOST }}
        REMOTE_PORT: ${{ inputs.NEXT_SSH_PORT }}
        ARGS: -aulrqtvz
        SOURCE: './wordpress/package.json ./wordpress/package-lock.json'
        TARGET: ${{ inputs.NEXT_SSH_PATH }}/wordpress/
        EXCLUDE: ''

    - id: ssh
      name: 'SSH Connection setup'
      uses: kuuak/ssh-action@main
      with:
        SSH_USER: ${{ inputs.NEXT_SSH_USER }}
        SSH_HOST: ${{ inputs.NEXT_SSH_HOST }}
        SSH_PORT: ${{ inputs.NEXT_SSH_PORT }}
        SSH_KEY: ${{ inputs.NEXT_SSH_PRIVATE_KEY }}

    - name: Restart PM2 app
      if: inputs.PM2_APP_NAME != ''
      shell: bash
      run: |
        ssh ${{ steps.ssh.outputs.SERVER }} \
           "cd ${{ inputs.NEXT_SSH_PATH }}; \
           pm2 restart ${{ inputs.PM2_APP_NAME }}"
